Added new controller: utisController
ZeroCR/ProHarold pull request #2
Opened 2019-06-19 04:34 UTC by har8360

2019-06-21 04:33 UTC, har8360 commented
@ZeroCR kindly proceed with PR

2019-06-27 05:25 UTC, ZeroCR requested changes

2019-06-27 05:25 UTC, ZeroCR commented on src/UtilsController.js
> +const esPalindromo = (palabra) => {
Mueva esta function a un nuevo archivo que se va a llamar UtilsService.js, en cual va a estar en el mismo directorio

2019-06-27 05:25 UTC, ZeroCR commented on src/UtilsController.js
> +	const nuevaPalabra={
esta variable no esta haciendo nada

2019-06-27 05:25 UTC, ZeroCR commented on src/UtilsController.js
> +	return nuevaPalabra;
no tiene sentido que esta variable se retorne en este punto

2019-07-05 02:46 UTC, har8360 commented on src/UtilsController.js
> +const esPalindromo = (palabra) => {
UtilsService era como el Modulo donde van todas la funciones que complian diferentes fines dentro de la aplicación, verdad, como me habías comentado.

2019-07-05 02:52 UTC, har8360 commented on src/UtilsController.js
> +const esPalindromo = (palabra) => {
y que dejo en el archivo de UtilsController.js ??

2019-07-05 03:01 UTC, har8360 commented on src/UtilsController.js
> +	const nuevaPalabra={
cual variable? nuevaPalabra?

2019-07-05 03:03 UTC, har8360 commented on src/UtilsController.js
> +	return nuevaPalabra;
tenemos que repasar lo de debuguear y la vara de hacer watch a las variables para ver como van mutando, la semana pasada lo intente y no pude

2019-07-08 04:24 UTC, ZeroCR commented on src/UtilsController.js
> +const esPalindromo = (palabra) => {
los Controllers guardan la definicion de los endpoints, y los Services guardan la logica de negocio

2019-07-08 04:25 UTC, ZeroCR commented on src/UtilsController.js
> +	const nuevaPalabra={
exacto

2019-07-24 04:45 UTC, merged